= GraalVM cli-app toy that sets slack profile name


== Step 7, upx on binary of step 1

Let's try `upx` on the binary that was produced in step 1.

.git history
[source]
----
...
* a208499 2020-11-18 21:38 G Document step 1 with slack read/rite operations (merged in #1)  brice.dutheil@gmail.com
*   3a821c3 2020-11-18 21:29 E Merge pull request #1  brice.dutheil@gmail.com
|\
| * a96a4bf 2020-11-18 19:25 G Adds write slack profile  brice.dutheil@gmail.com
| * e1d6a61 2020-11-18 17:37 G Adds reads slack profile  brice.dutheil@gmail.com
* | 8e0d529 2020-11-18 21:27 G Upgrade micronaut to 2.1.4  brice.dutheil@gmail.com
|/
* eb50d42 2020-11-18 11:38 G GraalVM commandline walking skeleton (wit micronaut 2)  brice.dutheil@gmail.com
(END)
----

----
$ git diff --binary HEAD a208499 | git apply
$ git checkout HEAD -- Dockerfile
$ git checkout HEAD -- README.adoc
$ git add src/main/resources/logback.xml
$ git add -u
$ git commit --message="Revert changes from step 6 to step 2"
[upx-micronaut 80ffddc] Revert changes from step 6 to step 2
 4 files changed, 66 insertions(+), 114 deletions(-)
 delete mode 100644 src/main/proguard-rules.txt
 create mode 100644 src/main/resources/logback.xml
----

Then let's try again `upx`

[docker, shell]
----
❯ docker run -it --rm \
  --mount=type=bind,source=$(pwd),target=/src \
  $(docker build -q -f Dockerfile .)
bash-4.2# ./gradlew clean nativeImage \
  && /upx-3.96-amd64_linux/upx -o build/native-image/{slack-upx,slack} \
  && ls -lh build/native-image/
...
total 69M
-rwxr-xr-x 1 root root 53M Nov 20 18:09 application
-rwxr-xr-x 1 root root 15M Nov 20 18:09 slack-upx
----

Thanks to `upx`, this time we go from 53 MiB to 15 MiB, I persist to think
it's still a bit too much for an application that barely perform a single HTTP
request, but it is way more acceptable in term of distribution.


== Step 6, upx

The last trick I can think of is using `upx` on the native executable.
Unfortunately this doesn't work on macOs, there's a
https://github.com/oracle/graal/issues/2830[closed issue] that
is supposed to be fixed in GraalVM 2020.3.0, but apparently this is still
an issue on macOs (
https://github.com/oracle/graal/issues/2830#issuecomment-731253931[[1\]]
https://github.com/oracle/graal/issues/2830#issuecomment-731262951[[2\]]
https://github.com/oracle/graal/issues/2830#issuecomment-731277407[[3\]]).

The upx step has only been tested on linux, more specifically Oracle Linux
with a graalvm install.

.GraalVM 2020.3.0 based Dockerfile
[source,dockerfile]
----
FROM oracle/graalvm-ce:20.3.0-java11

RUN yum install -y -q xz \
  && curl -sL -o - https://github.com/upx/upx/releases/download/v3.96/upx-3.96-amd64_linux.tar.xz | tar xJ \
  && gu install native-image \
  && mkdir /src

VOLUME /src
WORKDIR /src

CMD ["bash"]
----

Then quickly run the `Dockerfile` with the following command, the build
is very long due to the yum install of `xz`.

[source, shell]
----
docker run -it --rm \
  --mount=type=bind,source=$(pwd),target=/src \
  $(docker build -q -f Dockerfile .)
----

Then run in the bash command of this container :

[source, shell]
----
bash-4.2# ./gradlew nativeImage
Downloading https://services.gradle.org/distributions/gradle-6.7-bin.zip
.........10%..........20%..........30%..........40%..........50%.........60%..........70%..........80%..........90%..........100%

Welcome to Gradle 6.7!

Here are the highlights of this release:
 - File system watching is ready for production use
 - Declare the version of Java your build requires
 - Java 15 support

For more details see https://docs.gradle.org/6.7/release-notes.html

Starting a Gradle Daemon (subsequent builds will be faster)

> Task :nativeImage
[slack:149]    classlist:   2,667.03 ms,  0.96 GB
[slack:149]        (cap):     945.08 ms,  0.96 GB
[slack:149]        setup:   2,864.99 ms,  0.96 GB
[slack:149]     (clinit):     659.93 ms,  1.85 GB
[slack:149]   (typeflow):  19,460.83 ms,  1.85 GB
[slack:149]    (objects):  20,409.54 ms,  1.85 GB
[slack:149]   (features):   1,955.89 ms,  1.85 GB
[slack:149]     analysis:  43,560.66 ms,  1.85 GB
[slack:149]     universe:   1,384.76 ms,  1.85 GB
[slack:149]      (parse):   6,000.43 ms,  1.85 GB
[slack:149]     (inline):   9,922.65 ms,  2.70 GB
[slack:149]    (compile):  37,868.18 ms,  2.75 GB
[slack:149]      compile:  56,263.76 ms,  2.81 GB
[slack:149]        image:   4,536.83 ms,  2.80 GB
[slack:149]        write:   3,165.21 ms,  2.80 GB
[slack:149]      [total]: 114,740.56 ms,  2.80 GB

BUILD SUCCESSFUL in 2m 24s
5 actionable tasks: 1 executed, 4 up-to-date

bash-4.2# /upx-3.96-amd64_linux/upx -o build/native-image/{slack-upx,slack}
                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2020
UPX 3.96        Markus Oberhumer, Laszlo Molnar & John Reiser   Jan 23rd 2020

        File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------
  33437936 ->   9640936   28.83%   linux/amd64   slack-upx

Packed 1 file.
bash-4.2# ls -lah build/native-image
total 43M
drwxr-xr-x 4 root root  128 Nov 20 17:10 .
drwxr-xr-x 8 root root  256 Nov 20 17:02 ..
-rwxr-xr-x 1 root root  32M Nov 20 17:08 slack
-rwxr-xr-x 1 root root 9.2M Nov 20 17:08 slack-upx
bash-4.2# build/native-image/slack-upx
build/native-image/slack-upx -t read-profile
Slack Oauth token
(GET https://slack.com/api/users.profile.get?pretty=1) 200
{
    "ok": true,
    "profile": {
        "real_name": "\u0190\u0254\u0131\u0279q",
        "real_name_normalized": "\u0190\u0254i\u0279q",
...
----

So with `upx` the executable file size dropped to less than 10 MiB. This
compactness is way better for the distribution of a small command line tool.


== Step 5, remove libraries

First let's remove logback, replacing the logging calls, by a simpler
`System.out.printf`.

[source,shell]
----
$ ls -lh build/{libs,native-image}
build/libs:
Permissions Size User  Date Modified Name
.rw-r--r--  390k bric3 20 Nov 11:07  slack-set-profile-0.1-all.jar
.rw-r--r--  285k bric3 20 Nov 11:07  slack-set-profile-0.1-r8.jar
.rw-r--r--  279k bric3 20 Nov 11:07  slack-set-profile-0.1.jar

build/native-image:
Permissions Size User  Date Modified Name
.rwxr-xr-x   31M bric3 20 Nov 11:08  slack
----

There's definitively an improvement, but this only gained 5 MiB.

Ok let's try with by removing picocli. At this time the command line
arguments are very simple : two subcommands, one option that takes a
password or not, so it's easy to write with vanilla Java.

.Parsing the arguments
[source, java, role="primary"]
----
while ((arg = args.poll()) != null) {
    switch (arg) {
        case "-t":
        case "--token":
            tokenOption = true;
            break;
        case "read-profile":
            command = this::readUserProfile;
            break;
        case "write-profile":
            command = this::writeUserProfile;
            break;
        default:
            token = arg;
            break;
    }
}
----

.Reading the password on stdin
[source, java, role="secondary"]
----
if (token == null) {
    if (System.console() != null) {
        token = new String(System.console().readPassword("Slack Oauth token"));
    } else {
        System.out.print("Slack Oauth token: ");
        Scanner in = new Scanner(System.in);
        token = in.nextLine();
    }
}
----

Let's see what it means in the resulting size

[source, shell]
----
$ ./gradlew nativeImage
Starting a Gradle Daemon, 8 incompatible and 1 stopped Daemons could not be reused, use --status for details

> Task :nativeImage
[slack:72428]    classlist:   1,260.47 ms,  0.96 GB
[slack:72428]        (cap):   3,101.18 ms,  0.96 GB
[slack:72428]        setup:   6,799.68 ms,  0.96 GB
[slack:72428]     (clinit):     532.58 ms,  3.21 GB
[slack:72428]   (typeflow):  14,209.68 ms,  3.21 GB
[slack:72428]    (objects):  12,123.84 ms,  3.21 GB
[slack:72428]   (features):     746.32 ms,  3.21 GB
[slack:72428]     analysis:  28,292.35 ms,  3.21 GB
[slack:72428]     universe:     998.86 ms,  3.21 GB
[slack:72428]      (parse):   5,849.77 ms,  3.21 GB
[slack:72428]     (inline):  15,714.00 ms,  5.18 GB
[slack:72428]    (compile):  30,526.46 ms,  5.29 GB
[slack:72428]      compile:  54,166.83 ms,  5.29 GB
[slack:72428]        image:   3,009.64 ms,  5.33 GB
[slack:72428]        write:     818.88 ms,  5.33 GB
[slack:72428]      [total]:  95,531.54 ms,  5.33 GB

BUILD SUCCESSFUL in 1m 48s
8 actionable tasks: 6 executed, 2 up-to-date

$ l build/{libs,native-image}
build/libs:
Permissions Size User  Date Modified Name
.rw-r--r--  4.0k bric3 20 Nov 15:33  slack-set-profile-0.1-all.jar
.rw-r--r--  3.4k bric3 20 Nov 15:33  slack-set-profile-0.1-r8.jar
.rw-r--r--  3.7k bric3 20 Nov 15:33  slack-set-profile-0.1.jar

build/native-image:
Permissions Size User  Date Modified Name
.rwxr-xr-x   33M bric3 20 Nov 15:35  slack
----

It is still over 30 MiB ! This is definitely a lot for binary that is just
doing a single HTTP call per command (it doesn't even do JSON serialization
or deserialization).
However, the jar file sizes are merely 4 KiB. Shadowjar and R8 tasks could even be
removed.

== Step 4, try Jake Wharton approach with r8

Some time ago I read an
https://jakewharton.com/shrinking-a-kotlin-binary/[interesting article]
by https://twitter.com/JakeWharton[Jake Wharton] on shrinking the jar size.

Let's try to reduce the size of the shadowed jar to hopefully reduce
the GraalVM one. Currently, the shadowed jar file, is about 1.2 MiB.

.jar and shadowed jar sizes
[source, shell]
----
$ ./gradlew assemble

BUILD SUCCESSFUL in 2s
10 actionable tasks: 4 executed, 6 up-to-date

$ ls -lh build/libs/
Permissions Size User  Date Modified Name
.rw-r--r--  1.2M bric3 19 Nov 14:36  slack-set-profile-0.1-all.jar
.rw-r--r--  4.8k bric3 19 Nov  9:43  slack-set-profile-0.1.jar
----

The idea is to run _R8_, the android minifier, on the project
to remove non-needed code, since it is not an Android project,
I will use the same code as Jake Wharton in its
https://github.com/JakeWharton/dependency-tree-diff[dependency-tree-diff] project.

.Custom R8 gradle task
[source,gradle]
----
task r8(type: JavaExec) {
    dependsOn(configurations.named('runtimeClasspath'))
    dependsOn(shadowJar)
    inputs.files(shadowJar.archiveFile.get(), 'src/main/proguard-rules.txt')
    outputs.file(r8File)

    classpath(configurations.r8)
    main = 'com.android.tools.r8.R8'
    args = [
            '--release',
            '--classfile',
            '--output', r8File.toString(),
            '--pg-conf', 'src/main/proguard-rules.txt',
            '--lib', System.properties['java.home'].toString()
    ]
    doFirst {
        args += shadowJar.archiveFile.get()
    }
}
----

I'll need to tweak the proguard rules for this project. R8 uses the same
configuration as proguard, so I'll need to write a Proguard rules. Normally
proguard (and R8) is also used to obfuscate code. As I'm totally new
to proguard and R8, I'll start of again from the
https://github.com/JakeWharton/dependency-tree-diff[dependency-tree-diff] project.

.Proguard inspired by Jake Wharthon
[source, proguard]
----
-dontobfuscate
-allowaccessmodification
-keepattributes SourceFile, LineNumberTable, RuntimeVisibleAnnotations

# cli app
-keep class slack.set.profile.SlackSetProfileCommand {
    public static void main(java.lang.String[]);
}
----

This configuration alone is not enough and R8 warns because some classes
are missing, then R8 fails on this missing class `javax.mail.Authenticator`.
I searched a while, but simply adding the `-dontwarn` rules on the packages
that were warned about fixed this issue.

.Ignore missing classes
[source,proguard]
----
# Make r8 not fail on missing classes
-dontwarn javax.annotation.**
-dontwarn org.codehaus.groovy.**
-dontwarn groovy.**
-dontwarn javax.servlet.**
-dontwarn javax.mail.**
----

The R8 process completed, but the application failed at runtime because
too many classes or fields where missing. For this I needed to dive in the
proguard documentation, because R8 documentation is quite scarce.
Here are the sources I used :

* https://r8-docs.preemptive.com/ => Unofficial R8 documentation
* https://www.guardsquare.com/en/products/proguard/manual/examples =>
Official proguard documentation, here the example sections

First the application didn't start because fields of picocli classes
were stripped out. I wrote the following rule to keep fields and methods
annotated by Picocli annotations.

.Proguard configuration for picocli
[source, proguard]
----
# picocli
-keep class picocli.CommandLine.** { *;}
-keep @picocli.CommandLine$* class * { *; }
-keepclassmembers class ** {
  @picocli.CommandLine$* public protected private <methods>;
}
-keepclassmembers class * {
  @picocli.CommandLine$* public protected private <fields>;
}
-keepclassmembers class ** {
  @picocli.CommandLine$* <init>(...);
}
----

Fixing picocli made the application work, but logging was still off,
with some errors. So I crafted a small configuration that kept some
logback classes matching the `logback.xml` configuration.

.Logback encoder pattern
[source]
----
%cyan(%d{HH:mm:ss.SSS}) %gray([%thread]) %highlight(%-5level) %magenta(%logger{36}) - %msg%n
----

.Proguard configuration for logback
[source, proguard]
----
-keep class ch.qos.logback.core.ConsoleAppender { *; }
-keep class ch.qos.logback.classic.encoder.PatternLayoutEncoder { *; }
-keep class ch.qos.logback.classic.pattern.LineSeparatorConverter { *; }
-keep class ch.qos.logback.classic.pattern.MessageConverter { *; }
-keep class ch.qos.logback.classic.pattern.LoggerConverter { *; }
-keep class ch.qos.logback.classic.pattern.ThreadConverter { *; }
-keep class ch.qos.logback.classic.pattern.DateConverter { *; }
-keep class ch.qos.logback.classic.pattern.LevelConverter { *; }
-keep class ch.qos.logback.classic.pattern.color.HighlightingCompositeConverter { *; }
-keep class ch.qos.logback.core.pattern.color.* { *; }
----

So once everything was in order, did it help to further reduce the size of the binary ?

[source, shell]
----
$ ./gradlew r8Jar

BUILD SUCCESSFUL in 10s
4 actionable tasks: 1 executed, 3 up-to-date

$ ls -lh build/libs/
Permissions Size User  Date Modified Name
.rw-r--r--@ 597k bric3 19 Nov 17:29  slack-set-profile-0.1-r8.jar
----

The first thing to notice is the reduced size of the _minified_ jar
compared to shadowed jar, it's half the size. So for this step this is
already a success.

Next thing to do is to pass this minified jar to `native-image`.
For this I needed to create a dumb gradle `Jar` task because the custom
`r8` task is of type `JavaExec` and cannot be set to the `nativeImage.jarTask`
configuration field.

.Native image of the minified Jar with R8
[source, shell]
----
$ ./gradlew clean nativeImage

> Task :nativeImage
[slack:51762]    classlist:   1,175.12 ms,  0.96 GB
[slack:51762]        (cap):   2,750.34 ms,  0.96 GB
[slack:51762]        setup:   3,886.57 ms,  0.96 GB
[slack:51762]     (clinit):     458.99 ms,  2.32 GB
[slack:51762]   (typeflow):  12,516.27 ms,  2.32 GB
[slack:51762]    (objects):  13,514.93 ms,  2.32 GB
[slack:51762]   (features):     742.85 ms,  2.32 GB
[slack:51762]     analysis:  27,860.38 ms,  2.32 GB
[slack:51762]     universe:     924.52 ms,  2.32 GB
[slack:51762]      (parse):   3,451.93 ms,  3.16 GB
[slack:51762]     (inline):   5,874.31 ms,  4.05 GB
[slack:51762]    (compile):  23,216.78 ms,  4.97 GB
[slack:51762]      compile:  34,321.70 ms,  4.97 GB
[slack:51762]        image:   2,884.10 ms,  4.97 GB
[slack:51762]        write:     764.90 ms,  4.97 GB
[slack:51762]      [total]:  71,971.55 ms,  4.97 GB

BUILD SUCCESSFUL in 1m 22s
9 actionable tasks: 6 executed, 2 from cache, 1 up-to-date

$ ls -lh build/native-image/slack
Permissions Size User  Date Modified Name
.rwxr-xr-x   36M bric3 19 Nov 19:00  build/native-image/slack
----

It is still 36 MiB, so in the end minifying the jar did not help
to reduce the native image.

== Step 3, reducing size by removing micrometer plugin

As useful as micrometer, the plugin still adds a _bill-of-materials_,
however this bom actually depends on real Java dependencies.

.io.micronaut.library
> The Micronaut library plugin applies the following modifications to the build:
>
> * Applies the Micronaut Bill of Materials (BOM)
> * Applies the java-library plugin
> * Configures annotation processing for the current language (Groovy, Java or Kotlin)

.io.micronaut.application
> The Micronaut application plugin extends the Micronaut Library plugin and adds the following customizations:
> 
> * Instead of the java-library plugin the plugin applies the Gradle application plugin.
> * If the current JVM is GraalVM configures a nativeImage task
> * Correctly configures Gradle for continuous build

For this toy application, I don't want any of this but
the `nativeImage` task, possibly replaceable by a plugin listed
https://plugins.gradle.org/search?term=native-image[here].

https://github.com/micronaut-projects/micronaut-gradle-plugin/blob/v1.2.0/src/main/java/io/micronaut/gradle/graalvm/NativeImageTask.java[micronaut GraalVM task].

Now the question is : which plugin to use in order to replace this Micronaut task?
From their brief description here are the top four plugins, that may be good candidates,
but which one ?

I have decided to rule out plugins that downloads a GraalVM distribution,
regardless the current JDK is already a GraalVM.

* ❌ `com.formkiq.gradle.graalvm-native-plugin` 1.0.1 (11 November 2020)
* ❌ `com.palantir.graal` 0.7.2 (29 October 2020)

Then let's look at the other two:

* ✅ https://github.com/mike-neck/graalvm-native-image-plugin[`org.mikeneck.graalvm-native-image`] version 0.8.0 (09 August 2020)
+
This one appear very configurable, and requires just a few additional configuration,
that were srt by the micronaut task, like the no fallback.

The official GraalVM plugin, at this moment I didn't found any reference nor sources.

* ❌ `org.graalvm.plugin.native-image` 0.1.0-alpha2 (02 September 2020)

Although, it's likely similar to the current https://www.graalvm.org/reference-manual/native-image/NativeImageMavenPlugin/[GraalVM maven plugin].
So I'll just skipp this one.

So let's start with `org.mikeneck.graalvm-native-image`, the `nativeImage`
task will look like:

[source, gradle]
----
nativeImage {
    executableName = "slack"
    mainClass = application.mainClass.get()
    graalVmHome = System.getProperty('java.home')
    arguments(
            '--no-fallback',
            "--allow-incomplete-classpath",
    )
}
----

[source, shell]
----
$ ls -lah build/native-image/
Permissions Size User  Date Modified Name
.rwxr-xr-x   25M bric3 19 Nov 10:58  slack
----

Better, but when the tool is run, we trip over the usual JCA security services issue
(https://github.com/oracle/graal/blob/release/graal-vm/20.3/substratevm/JCASecurityServices.md[they are not included by default]).

[source, shell]
----
$ build/native-image/slack
Exception in thread "main" java.lang.InternalError: java.security.NoSuchAlgorithmException: class configured for SSLContext (provider: SunJSSE) cannot be found.
----

So we need to pass either `--enable-all-security-services` or `--enable-https` arguments.

.With `--enable-all-security-services`
[source, shell]
----
$ ls -lah build/native-image/slack
Permissions Size User  Date Modified Name
.rwxr-xr-x   37M bric3 19 Nov 11:01  build/native-image/slack
----

.With `--enable-https`
[source, shell]
----
$ ls -lah build/native-image/slack
Permissions Size User  Date Modified Name
.rwxr-xr-x   38M bric3 19 Nov 11:48  build/native-image/slack
----

37 MiB and 38 MiB it's a tad more than what we had with the micronaut plugin.
I'm not sure how micronaut is doing in this regard as the task don't seem to
pass either of these options.
That also means that the concrete transitive dependencies in the micronaut bom don't
really count, probably due to micronaut doing a really fine job there.

The conclusion of this step is that this approach don't work as I would like,
but it matches what I found
https://gist.github.com/bric3/a5d18934ed1dc7fde36c48eace70c4f2[early in June 2020 when playing with `SSLPoke`],
adding JCA services adds around 12 MiB to the native image.


== Step 2, reducing  size by removing micrometer dependencies

[source, shell]
----
$ ./gradlew :dependencies --configuration runtimeClasspath

> Task :dependencies

------------------------------------------------------------
Root project
------------------------------------------------------------

runtimeClasspath - Runtime classpath of source set 'main'.
+--- io.micronaut:micronaut-validation -> 2.1.4
|    +--- org.slf4j:slf4j-api:1.7.26
|    +--- io.micronaut:micronaut-inject:2.1.4
|    |    +--- org.slf4j:slf4j-api:1.7.26
|    |    +--- javax.annotation:javax.annotation-api:1.3.2
|    |    +--- javax.inject:javax.inject:1
|    |    +--- io.micronaut:micronaut-core:2.1.4
|    |    |    +--- org.slf4j:slf4j-api:1.7.26
|    |    |    +--- org.reactivestreams:reactive-streams:1.0.3
|    |    |    \--- com.github.spotbugs:spotbugs-annotations:4.0.3
|    |    |         \--- com.google.code.findbugs:jsr305:3.0.2
|    |    \--- org.yaml:snakeyaml:1.26
|    +--- io.micronaut:micronaut-http:2.1.4
|    |    +--- org.slf4j:slf4j-api:1.7.26
|    |    \--- io.micronaut:micronaut-inject:2.1.4 (*)
|    \--- javax.validation:validation-api:2.0.1.Final
+--- io.micronaut:micronaut-runtime -> 2.1.4
|    +--- org.slf4j:slf4j-api:1.7.26
|    +--- io.micronaut:micronaut-http:2.1.4 (*)
|    +--- io.micronaut:micronaut-inject:2.1.4 (*)
|    +--- io.micronaut:micronaut-aop:2.1.4
|    |    +--- org.slf4j:slf4j-api:1.7.26
|    |    +--- io.micronaut:micronaut-inject:2.1.4 (*)
|    |    \--- io.micronaut:micronaut-core:2.1.4 (*)
|    +--- javax.validation:validation-api:2.0.1.Final
|    +--- com.fasterxml.jackson.core:jackson-databind:2.11.2
|    |    +--- com.fasterxml.jackson.core:jackson-annotations:2.11.2
|    |    \--- com.fasterxml.jackson.core:jackson-core:2.11.2
|    +--- io.reactivex.rxjava2:rxjava:2.2.10
|    |    \--- org.reactivestreams:reactive-streams:1.0.2 -> 1.0.3
|    +--- com.fasterxml.jackson.datatype:jackson-datatype-jdk8:2.11.2
|    |    +--- com.fasterxml.jackson.core:jackson-core:2.11.2
|    |    \--- com.fasterxml.jackson.core:jackson-databind:2.11.2 (*)
|    \--- com.fasterxml.jackson.datatype:jackson-datatype-jsr310:2.11.2
|         +--- com.fasterxml.jackson.core:jackson-annotations:2.11.2
|         +--- com.fasterxml.jackson.core:jackson-core:2.11.2
|         \--- com.fasterxml.jackson.core:jackson-databind:2.11.2 (*)
+--- info.picocli:picocli -> 4.5.1
+--- io.micronaut.picocli:micronaut-picocli -> 3.0.0
|    +--- io.micronaut:micronaut-bom:2.0.1 -> 2.1.4
|    |    +--- io.micronaut.views:micronaut-views-bom:2.0.1
|    |    +--- io.micronaut.groovy:micronaut-groovy-bom:2.1.0
|    |    |    \--- org.codehaus.groovy:groovy-bom:3.0.3
|    |    +--- io.micronaut.test:micronaut-test-bom:2.1.1
|    |    |    +--- org.junit:junit-bom:5.7.0
|    |    |    \--- org.spockframework:spock-bom:2.0-M3-groovy-3.0
|    |    +--- io.micronaut.data:micronaut-data-bom:2.1.1
|    |    +--- io.micronaut.oraclecloud:micronaut-oraclecloud-bom:1.0.0
|    |    +--- io.netty:netty-bom:4.1.54.Final
|    |    +--- io.ktor:ktor-bom:1.4.0
|    |    +--- org.codehaus.groovy:groovy-bom:3.0.3
|    |    +--- io.micrometer:micrometer-bom:1.5.5
|    |    +--- org.junit:junit-bom:5.7.0
|    |    +--- com.fasterxml.jackson:jackson-bom:2.11.2
|    |    |    +--- com.fasterxml.jackson.core:jackson-databind:2.11.2 (c)
|    |    |    +--- com.fasterxml.jackson.datatype:jackson-datatype-jdk8:2.11.2 (c)
|    |    |    +--- com.fasterxml.jackson.datatype:jackson-datatype-jsr310:2.11.2 (c)
|    |    |    +--- com.fasterxml.jackson.core:jackson-annotations:2.11.2 (c)
|    |    |    \--- com.fasterxml.jackson.core:jackson-core:2.11.2 (c)
|    |    +--- io.grpc:grpc-bom:1.32.1
|    |    +--- com.google.protobuf:protobuf-bom:3.13.0
|    |    +--- io.micronaut:micronaut-inject:2.1.4 (c)
|    |    +--- io.micronaut:micronaut-runtime:2.1.4 (c)
|    |    +--- io.micronaut:micronaut-validation:2.1.4 (c)
|    |    +--- javax.annotation:javax.annotation-api:1.3.2 (c)
|    |    +--- io.micronaut.picocli:micronaut-picocli:3.0.0 (c)
|    |    +--- info.picocli:picocli:4.5.1 (c)
|    |    +--- ch.qos.logback:logback-classic:1.2.3 (c)
|    |    +--- org.slf4j:slf4j-api:1.7.26 (c)
|    |    +--- io.micronaut:micronaut-core:2.1.4 (c)
|    |    +--- org.yaml:snakeyaml:1.26 (c)
|    |    +--- io.micronaut:micronaut-http:2.1.4 (c)
|    |    +--- io.micronaut:micronaut-aop:2.1.4 (c)
|    |    +--- javax.validation:validation-api:2.0.1.Final (c)
|    |    +--- io.reactivex.rxjava2:rxjava:2.2.10 (c)
|    |    +--- org.reactivestreams:reactive-streams:1.0.3 (c)
|    |    +--- com.github.spotbugs:spotbugs-annotations:4.0.3 (c)
|    |    \--- com.google.code.findbugs:jsr305:3.0.2 (c)
|    +--- io.micronaut:micronaut-inject:2.0.1 -> 2.1.4 (*)
|    +--- io.micronaut:micronaut-runtime:2.0.1 -> 2.1.4 (*)
|    \--- info.picocli:picocli:4.5.1
+--- javax.annotation:javax.annotation-api -> 1.3.2
+--- io.micronaut:micronaut-inject -> 2.1.4 (*)
+--- io.micronaut:micronaut-bom:2.1.4 (*)
\--- ch.qos.logback:logback-classic -> 1.2.3
     +--- ch.qos.logback:logback-core:1.2.3
     \--- org.slf4j:slf4j-api:1.7.25 -> 1.7.26

(c) - dependency constraint
(*) - dependencies omitted (listed previously)

A web-based, searchable dependency report is available by adding the --scan option.

BUILD SUCCESSFUL in 1s
1 actionable task: 1 executed
----


Even if the project only added the asciidoctor and graalvm features,
there's a few dependencies by default.

Removing all explicit depencencies

.removing explicit depdencies
[source, diff]
----
     annotationProcessor("info.picocli:picocli-codegen:4.2.0")
     compileOnly("org.graalvm.nativeimage:svm")
-    implementation("io.micronaut:micronaut-validation")
-    implementation("io.micronaut:micronaut-runtime")
     implementation("info.picocli:picocli")
-    implementation("io.micronaut.picocli:micronaut-picocli")
-    implementation("javax.annotation:javax.annotation-api")
----


[source, shell]
----
$ ./gradlew :dependencies --configuration runtimeClasspath

> Task :dependencies

------------------------------------------------------------
Root project
------------------------------------------------------------

runtimeClasspath - Runtime classpath of source set 'main'.
+--- info.picocli:picocli -> 4.5.1
+--- io.micronaut:micronaut-inject -> 2.1.4
|    +--- org.slf4j:slf4j-api:1.7.26
|    +--- javax.annotation:javax.annotation-api:1.3.2
|    +--- javax.inject:javax.inject:1
|    +--- io.micronaut:micronaut-core:2.1.4
|    |    +--- org.slf4j:slf4j-api:1.7.26
|    |    +--- org.reactivestreams:reactive-streams:1.0.3
|    |    \--- com.github.spotbugs:spotbugs-annotations:4.0.3
|    |         \--- com.google.code.findbugs:jsr305:3.0.2
|    \--- org.yaml:snakeyaml:1.26
+--- io.micronaut:micronaut-bom:2.1.4
|    +--- io.micronaut.views:micronaut-views-bom:2.0.1
|    +--- io.micronaut.groovy:micronaut-groovy-bom:2.1.0
|    |    \--- org.codehaus.groovy:groovy-bom:3.0.3
|    +--- io.micronaut.test:micronaut-test-bom:2.1.1
|    |    +--- org.junit:junit-bom:5.7.0
|    |    \--- org.spockframework:spock-bom:2.0-M3-groovy-3.0
|    +--- io.micronaut.data:micronaut-data-bom:2.1.1
|    +--- io.micronaut.oraclecloud:micronaut-oraclecloud-bom:1.0.0
|    +--- io.netty:netty-bom:4.1.54.Final
|    +--- io.ktor:ktor-bom:1.4.0
|    +--- org.codehaus.groovy:groovy-bom:3.0.3
|    +--- io.micrometer:micrometer-bom:1.5.5
|    +--- org.junit:junit-bom:5.7.0
|    +--- com.fasterxml.jackson:jackson-bom:2.11.2
|    +--- io.grpc:grpc-bom:1.32.1
|    +--- com.google.protobuf:protobuf-bom:3.13.0
|    +--- io.micronaut:micronaut-inject:2.1.4 (c)
|    +--- info.picocli:picocli:4.5.1 (c)
|    +--- ch.qos.logback:logback-classic:1.2.3 (c)
|    +--- org.slf4j:slf4j-api:1.7.26 (c)
|    +--- javax.annotation:javax.annotation-api:1.3.2 (c)
|    +--- io.micronaut:micronaut-core:2.1.4 (c)
|    +--- org.yaml:snakeyaml:1.26 (c)
|    +--- org.reactivestreams:reactive-streams:1.0.3 (c)
|    +--- com.github.spotbugs:spotbugs-annotations:4.0.3 (c)
|    \--- com.google.code.findbugs:jsr305:3.0.2 (c)
\--- ch.qos.logback:logback-classic -> 1.2.3
     +--- ch.qos.logback:logback-core:1.2.3
     \--- org.slf4j:slf4j-api:1.7.25 -> 1.7.26

(c) - dependency constraint
(*) - dependencies omitted (listed previously)

A web-based, searchable dependency report is available by adding the --scan option.

BUILD SUCCESSFUL in 1s
1 actionable task: 1 executed
----

This leads to quite few ~ 16 MiB saved :

.lighter native image
[source, shell]
----
❯ ./gradlew nativeImage

> Task :compileJava
Note: ReflectConfigGen writing to: CLASS_OUTPUT/META-INF/native-image/picocli-generated/reflect-config.json
Note: ResourceConfigGen writing to: CLASS_OUTPUT/META-INF/native-image/picocli-generated/resource-config.json
Note: ProxyConfigGen writing to: CLASS_OUTPUT/META-INF/native-image/picocli-generated/proxy-config.json

> Task :nativeImage
[application:16014]    classlist:   1,525.12 ms,  0.96 GB
[application:16014]        (cap):   3,379.97 ms,  0.96 GB
[application:16014]        setup:   4,416.23 ms,  0.96 GB
[application:16014]     (clinit):     530.59 ms,  4.62 GB
[application:16014]   (typeflow):  14,808.15 ms,  4.62 GB
[application:16014]    (objects):  13,375.10 ms,  4.62 GB
[application:16014]   (features):     912.96 ms,  4.62 GB
[application:16014]     analysis:  30,346.45 ms,  4.62 GB
[application:16014]     universe:     926.49 ms,  4.62 GB
[application:16014]      (parse):   4,099.46 ms,  4.62 GB
[application:16014]     (inline):   7,206.29 ms,  5.38 GB
[application:16014]    (compile):  23,836.20 ms,  5.20 GB
[application:16014]      compile:  37,356.28 ms,  5.20 GB
[application:16014]        image:   3,355.86 ms,  5.20 GB
[application:16014]        write:     960.86 ms,  5.20 GB
[application:16014]      [total]:  79,031.79 ms,  5.20 GB
Native Image written to: /Users/bric3/opensource/slack-set-profile/build/native-image/application

BUILD SUCCESSFUL in 1m 22s
3 actionable tasks: 2 executed, 1 up-to-date
❯ ls -lah build/native-image/application
Permissions Size User  Date Modified Name
.rwxr-xr-x   38M bric3 18 Nov 23:04  build/native-image/application
----

== Step 1, adds simple HTTP read/write operation

The goal is to read or write to the slack user profile,
for that there's two subcommands

[source,java]
----
    @Command(name = "read-profile", description = "Read slack user profile")
    void readUserProfile() {
----

[source,java]
----
    @Command(name = "write-profile", description = "Read slack user profile")
    void writeUserProfile() {
----

They both use the JDK `HttpClient` introduced in JDK 11.
Let us see what it does to add two new picocli method subcommands
with `HttpClient` ?

.binary size with subcommands
[source, shell]
----
$  ls -lah build/native-image/application
Permissions Size User  Date Modified Name
.rwxr-xr-x   54M bric3 18 Nov 21:33  build/native-image/application
----

== Step 0, a walking skeleton

Use the micronaut command line starter to create the cli application

.Micronaut starter
[source, shell]
----
$ mn create-cli-app --features=graalvm,asciidoctor --jdk=11 slack-set-profile
| Application created at /Users/bric3/opensource/slack-set-profile
$ cd slack-set-profile
----

Then setup GraalVM for this project, I'm using https://asdf-vm.com/[asdf-vm]
with the https://github.com/halcyon/asdf-java[asdf-java plugin] to manage my
JDK versions. Then it's necessary to download the `native-image` binary using
the specific GraalVM `gu` tool.

.Use GraalVM with `native-image`
[source, shell]
----
$ asdf local java graalvm-20.3.0+java11
$ gu install native-image
Downloading: Component catalog from www.graalvm.org
Processing Component: Native Image
Downloading: Component native-image: Native Image  from github.com
Installing new component: Native Image (org.graalvm.native-image, version 20.3.0)
----

Since the micronaut starter generated a sample class, it's already possible
to use the `nativeImage` task (that is declared by the `io.micronaut.application`
gradle plugin).

[source, shell]
----
$ ./gradlew nativeImage
Starting a Gradle Daemon, 2 incompatible Daemons could not be reused, use --status for details

> Task :nativeImage
[application:5132]    classlist:   2,643.56 ms,  0.96 GB
[application:5132]        (cap):   3,351.71 ms,  0.94 GB
[application:5132]        setup:   5,624.55 ms,  0.94 GB
[application:5132]     (clinit):   1,123.83 ms,  3.87 GB
[application:5132]   (typeflow):  20,613.01 ms,  3.87 GB
[application:5132]    (objects):  25,885.88 ms,  3.87 GB
[application:5132]   (features):   2,753.84 ms,  3.87 GB
[application:5132]     analysis:  52,584.51 ms,  3.87 GB
[application:5132]     universe:   2,365.85 ms,  3.88 GB
[application:5132]      (parse):   6,115.11 ms,  3.88 GB
[application:5132]     (inline):  13,036.22 ms,  5.48 GB
[application:5132]    (compile):  42,139.93 ms,  5.67 GB
[application:5132]      compile:  64,370.44 ms,  5.67 GB
[application:5132]        image:   6,289.82 ms,  5.62 GB
[application:5132]        write:   1,752.41 ms,  5.62 GB
[application:5132]      [total]: 136,033.63 ms,  5.62 GB
Native Image written to: /Users/bric3/opensource/slack-set-profile/build/native-image/application

BUILD SUCCESSFUL in 2m 27s
3 actionable tasks: 1 executed, 2 up-to-date

$ ls -lah build/native-image/application
Permissions Size User  Date Modified Name
.rwxr-xr-x   51M bric3 18 Nov 11:20  build/native-image/application

$ build/native-image/application -h
11:22:37.206 [main] INFO  i.m.context.env.DefaultEnvironment - Established active environments: [cli]
Usage: slack-set-profile [-hvV]
...
  -h, --help      Show this help message and exit.
  -v, --verbose   ...
  -V, --version   Print version information and exit.
----

This generated a binary of 50 MiB that does nothing but prints help.
But, it's a standalone executable.

As expected the native image is around 2 orders of magnitude faster than
starting a cold JVM (with the default options).

.Stupid benchmarks
[source, shell]
----
$ hyperfine "build/native-image/application -h"
Benchmark #1: build/native-image/application -h
  Time (mean ± σ):      22.5 ms ±   3.6 ms    [User: 9.6 ms, System: 9.7 ms]
  Range (min … max):    19.8 ms …  59.9 ms    123 runs

  Warning: Statistical outliers were detected. Consider re-running this benchmark on a quiet PC without any interferences from other programs. It might help to use the '--warmup' or '--prepare' options.

$ hyperfine "java -jar build/libs/slack-set-profile-0.1-all.jar -h"
Benchmark #1: java -jar build/libs/slack-set-profile-0.1-all.jar -h
  Time (mean ± σ):      1.190 s ±  0.025 s    [User: 1.505 s, System: 0.263 s]
  Range (min … max):    1.166 s …  1.244 s    10 runs


----




